FROM node:20-alpine AS build
WORKDIR /workspace
COPY package*.json ./
COPY nx.json tsconfig.base.json ./
COPY apps ./apps
COPY libs ./libs
RUN npm install --no-audit --no-fund
RUN npx nx build web --configuration development

FROM nginx:1.27-alpine AS runtime
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/dist/apps/web/browser /usr/share/nginx/html
EXPOSE 80
