/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currency/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CurrencyController_getRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все организации */
        get: operations["OrganizationsController_findAll"];
        put?: never;
        /** Создать новую организацию */
        post: operations["OrganizationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить организацию по ID */
        get: operations["OrganizationsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить организацию */
        delete: operations["OrganizationsController_remove"];
        options?: never;
        head?: never;
        /** Обновить организацию */
        patch: operations["OrganizationsController_update"];
        trace?: never;
    };
    "/organizations/import-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт организаций из Excel (лист "Организации") */
        post: operations["OrganizationsController_importExcel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/upload-logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrganizationsController_uploadLogo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/upload-signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrganizationsController_uploadSignature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/upload-stamp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrganizationsController_uploadStamp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить всех клиентов */
        get: operations["ClientsController_findAll"];
        put?: never;
        /** Создать клиента */
        post: operations["ClientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить клиента по ID */
        get: operations["ClientsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить клиента */
        delete: operations["ClientsController_remove"];
        options?: never;
        head?: never;
        /** Обновить клиента */
        patch: operations["ClientsController_update"];
        trace?: never;
    };
    "/clients/import-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт клиентов из Excel (лист "Клиенты") */
        post: operations["ClientsController_importExcel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findAllCategories"];
        put?: never;
        post: operations["ProductsController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск продуктов по названию */
        get: operations["ProductsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все продукты */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Создать новый продукт */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить продукт по ID */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /** Обновить продукт по ID */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/products/export/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_exportToExcel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/import/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductsController_importXlsx"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/import-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт товаров из Excel (лист "Товары") */
        post: operations["ProductsController_importExcel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProposalsController_findAll"];
        put?: never;
        post: operations["ProposalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/preview-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProposalsController_previewPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProposalsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ProposalsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ProposalsController_update"];
        trace?: never;
    };
    "/proposals/{id}/send-to-yougile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProposalsController_sendToYougile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/yougile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ProposalsController_removeFromYougile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProposalsController_generatePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf-templates/base/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PdfTemplatesController_getBaseTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf-templates/organization/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PdfTemplatesController_getByOrganization"];
        put: operations["PdfTemplatesController_upsert"];
        post?: never;
        delete: operations["PdfTemplatesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход через Google ID Token */
        post: operations["AuthController_googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация по email и паролю */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по email и паролю */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий авторизованный пользователь */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей (только админ) */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Создать пользователя с паролем (только админ) */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить роль пользователя (только админ) */
        patch: operations["UsersController_updateRole"];
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить пользователя (только админ) */
        delete: operations["UsersController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_findAll"];
        put?: never;
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/categories/import-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт категорий из Excel (лист "Категории") */
        post: operations["CategoriesController_importExcel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить права доступа по ролям (для всех авторизованных) */
        get: operations["RolesController_getPermissions"];
        /** Обновить права доступа (только админ) */
        put: operations["RolesController_updatePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать приглашение пользователя (только админ) */
        post: operations["RolesController_createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/all-xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExcelController_exportAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/all-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Импорт ВСЕХ данных из одного Excel (crm-data.xlsx) */
        post: operations["ImportController_importAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/realtime/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RealtimeController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все документы настроек */
        get: operations["SettingsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить глобальные настройки */
        get: operations["SettingsController_getGlobal"];
        put?: never;
        /** Создать настройки */
        post: operations["SettingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить глобальные настройки */
        patch: operations["SettingsController_updateGlobal"];
        trace?: never;
    };
    "/settings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить настройки по ID */
        get: operations["SettingsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить настройки */
        delete: operations["SettingsController_remove"];
        options?: never;
        head?: never;
        /** Обновить настройки по ID */
        patch: operations["SettingsController_update"];
        trace?: never;
    };
    "/part-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все типы частей */
        get: operations["PartTypesController_findAll"];
        put?: never;
        /** Создать тип части */
        post: operations["PartTypesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/part-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить тип части */
        delete: operations["PartTypesController_remove"];
        options?: never;
        head?: never;
        /** Обновить тип части */
        patch: operations["PartTypesController_update"];
        trace?: never;
    };
    "/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все материалы */
        get: operations["MaterialsController_findAll"];
        put?: never;
        /** Создать материал */
        post: operations["MaterialsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить материал */
        delete: operations["MaterialsController_remove"];
        options?: never;
        head?: never;
        /** Обновить материал */
        patch: operations["MaterialsController_update"];
        trace?: never;
    };
    "/product-specification/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить состав товара */
        get: operations["ProductSpecificationController_getForProduct"];
        /** Полностью заменить состав товара */
        put: operations["ProductSpecificationController_replaceForProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrganizationDto: {
            /**
             * @description Название организации (краткое)
             * @example ООО "СпортСтройЮг"
             */
            name: string;
            /**
             * @description Полное наименование
             * @example Общество с ограниченной ответственностью «СпортСтройЮг»
             */
            fullName?: string;
            /**
             * @description Краткое наименование
             * @example ООО «СпортСтройЮг»
             */
            shortName?: string;
            /**
             * @description ИНН
             * @example 2312308098
             */
            inn?: string;
            /**
             * @description КПП
             * @example 231201001
             */
            kpp?: string;
            /**
             * @description ОГРН
             * @example 1222300008358
             */
            ogrn?: string;
            /**
             * @description ОКПО
             * @example 98449631
             */
            okpo?: string;
            /**
             * @description ОКВЭД
             * @example 41.20
             */
            okved?: string;
            /**
             * @description Юридический адрес
             * @example 350065, г. Краснодар, ул. им. Валерия Гассия, д. 17, пом. 57, ком. 1
             */
            legalAddress?: string;
            /**
             * @description Фактический адрес
             * @example 350004, г. Краснодар, ул. Кожевенная, д. 54/2
             */
            actualAddress?: string;
            /**
             * @description Почтовый адрес
             * @example 350089, г. Краснодар, ул.им.70-летия Октября, д. 34/3, оф. 31
             */
            postalAddress?: string;
            /**
             * @description Банк
             * @example Краснодарское отделение № 8619 ПАО «СБЕРБАНК» г. Краснодар
             */
            bankName?: string;
            /**
             * @description БИК
             * @example 040349602
             */
            bik?: string;
            /**
             * @description Расчетный счёт
             * @example 40702810730000021582
             */
            settlementAccount?: string;
            /**
             * @description Корреспондентский счёт
             * @example 30101810100000000602
             */
            correspondentAccount?: string;
            /**
             * @description Телефон
             * @example 8 (918) 633-91-91
             */
            phone?: string;
            /**
             * @description Доп. телефон
             * @example 8 (928) 333-91-91
             */
            extraPhone?: string;
            /**
             * @description E-mail
             * @example sportstroy_yug@mail.ru
             */
            email?: string;
            /**
             * @description Сайт
             * @example sportin-yug.ru
             */
            website?: string;
            /**
             * @description ФИО руководителя
             * @example Сизова Светлана Николаевна
             */
            directorFio?: string;
            /**
             * @description ФИО руководителя (сокращённое)
             * @example Сизова С.Н.
             */
            directorFioShort?: string;
            /**
             * @description Должность руководителя
             * @example Генеральный директор
             */
            directorPosition?: string;
            /**
             * @description Действует на основании
             * @example Действует на основании Устава
             */
            directorActingOn?: string;
            /**
             * @description Рег. номер ФСС
             * @example 2301048301
             */
            fssNumber?: string;
            /**
             * @description Рег. номер ПФР
             * @example 033-017-133104
             */
            pfrNumber?: string;
            /**
             * @description Логотип
             * @example https://cdn.com/logo.png
             */
            logoUrl?: string;
            /**
             * @description Подпись
             * @example https://cdn.com/signature.png
             */
            signatureUrl?: string;
            /**
             * @description Печать
             * @example https://cdn.com/stamp.png
             */
            stampUrl?: string;
            /**
             * @description Заметки
             * @example Производство и поставка спортивного оборудования
             */
            notes?: string;
            /**
             * @description Наценка
             * @example 20
             */
            markup?: number;
            /**
             * @description Префикс КП
             * @example КП-ССЮ-
             */
            prefix?: string;
            /**
             * @description НДС, %
             * @example 20
             */
            vatPercent?: number;
            /**
             * @description Цвет акцента
             * @example #1d4ed8
             */
            accentColor?: string;
            /**
             * @description Реквизиты (текстом)
             * @example ИНН 12345678, КПП...
             */
            requisites?: string;
        };
        OrganizationDto: {
            /**
             * @description ID
             * @example 65f8a1b2c3d4e5f6a7b8c9d0
             */
            _id: string;
            /**
             * @description Название организации (краткое)
             * @example ООО "Моя Компания"
             */
            name: string;
            /**
             * @description Логотип
             * @example https://cdn.com/logo.png
             */
            logoUrl?: string;
            /**
             * @description Подпись
             * @example https://cdn.com/signature.png
             */
            signatureUrl?: string;
            /**
             * @description Печать
             * @example https://cdn.com/stamp.png
             */
            stampUrl?: string;
            /**
             * @description Реквизиты (текстом)
             * @example ИНН 12345678, КПП...
             */
            requisites?: string;
            /**
             * @description Наценка
             * @example 20
             */
            markup?: number;
            /**
             * @description Префикс КП
             * @example КП-
             */
            prefix?: string;
            /**
             * @description Дата создания
             * @example 2025-02-28T12:00:00Z
             */
            createdAt: string;
            /**
             * @description Дата обновления
             * @example 2025-02-28T12:00:00Z
             */
            updatedAt: string;
        };
        UpdateOrganizationDto: {
            /**
             * @description Название организации (краткое)
             * @example ООО "СпортСтройЮг"
             */
            name?: string;
            /**
             * @description Полное наименование
             * @example Общество с ограниченной ответственностью «СпортСтройЮг»
             */
            fullName?: string;
            /**
             * @description Краткое наименование
             * @example ООО «СпортСтройЮг»
             */
            shortName?: string;
            /**
             * @description ИНН
             * @example 2312308098
             */
            inn?: string;
            /**
             * @description КПП
             * @example 231201001
             */
            kpp?: string;
            /**
             * @description ОГРН
             * @example 1222300008358
             */
            ogrn?: string;
            /**
             * @description ОКПО
             * @example 98449631
             */
            okpo?: string;
            /**
             * @description ОКВЭД
             * @example 41.20
             */
            okved?: string;
            /**
             * @description Юридический адрес
             * @example 350065, г. Краснодар, ул. им. Валерия Гассия, д. 17, пом. 57, ком. 1
             */
            legalAddress?: string;
            /**
             * @description Фактический адрес
             * @example 350004, г. Краснодар, ул. Кожевенная, д. 54/2
             */
            actualAddress?: string;
            /**
             * @description Почтовый адрес
             * @example 350089, г. Краснодар, ул.им.70-летия Октября, д. 34/3, оф. 31
             */
            postalAddress?: string;
            /**
             * @description Банк
             * @example Краснодарское отделение № 8619 ПАО «СБЕРБАНК» г. Краснодар
             */
            bankName?: string;
            /**
             * @description БИК
             * @example 040349602
             */
            bik?: string;
            /**
             * @description Расчетный счёт
             * @example 40702810730000021582
             */
            settlementAccount?: string;
            /**
             * @description Корреспондентский счёт
             * @example 30101810100000000602
             */
            correspondentAccount?: string;
            /**
             * @description Телефон
             * @example 8 (918) 633-91-91
             */
            phone?: string;
            /**
             * @description Доп. телефон
             * @example 8 (928) 333-91-91
             */
            extraPhone?: string;
            /**
             * @description E-mail
             * @example sportstroy_yug@mail.ru
             */
            email?: string;
            /**
             * @description Сайт
             * @example sportin-yug.ru
             */
            website?: string;
            /**
             * @description ФИО руководителя
             * @example Сизова Светлана Николаевна
             */
            directorFio?: string;
            /**
             * @description ФИО руководителя (сокращённое)
             * @example Сизова С.Н.
             */
            directorFioShort?: string;
            /**
             * @description Должность руководителя
             * @example Генеральный директор
             */
            directorPosition?: string;
            /**
             * @description Действует на основании
             * @example Действует на основании Устава
             */
            directorActingOn?: string;
            /**
             * @description Рег. номер ФСС
             * @example 2301048301
             */
            fssNumber?: string;
            /**
             * @description Рег. номер ПФР
             * @example 033-017-133104
             */
            pfrNumber?: string;
            /**
             * @description Логотип
             * @example https://cdn.com/logo.png
             */
            logoUrl?: string;
            /**
             * @description Подпись
             * @example https://cdn.com/signature.png
             */
            signatureUrl?: string;
            /**
             * @description Печать
             * @example https://cdn.com/stamp.png
             */
            stampUrl?: string;
            /**
             * @description Заметки
             * @example Производство и поставка спортивного оборудования
             */
            notes?: string;
            /**
             * @description Наценка
             * @example 20
             */
            markup?: number;
            /**
             * @description Префикс КП
             * @example КП-ССЮ-
             */
            prefix?: string;
            /**
             * @description НДС, %
             * @example 20
             */
            vatPercent?: number;
            /**
             * @description Цвет акцента
             * @example #1d4ed8
             */
            accentColor?: string;
            /**
             * @description Реквизиты (текстом)
             * @example ИНН 12345678, КПП...
             */
            requisites?: string;
        };
        CreateClientDto: {
            /**
             * @description Название / ФИО клиента
             * @example ООО "Ромашка"
             */
            name: string;
            /**
             * @description ИНН
             * @example 2312308098
             */
            inn?: string;
            /**
             * @description КПП
             * @example 231201001
             */
            kpp?: string;
            /**
             * @description Контактное лицо
             * @example Иванов Иван Иванович
             */
            contactPerson?: string;
            /**
             * @description Телефон
             * @example +7 (918) 123-45-67
             */
            phone?: string;
            /**
             * @description E-mail
             * @example client@mail.ru
             */
            email?: string;
            /**
             * @description Реквизиты клиента
             * @example ИНН 2312..., КПП ...
             */
            requisites?: string;
            /**
             * @description Адрес
             * @example г. Краснодар, ул. Примерная, д. 1
             */
            address?: string;
            /**
             * @description Заметки
             * @example Заметки по клиенту
             */
            notes?: string;
            /**
             * @description Скидка, %
             * @example 5
             */
            discount?: number;
            /**
             * @description Наценка клиента, %
             * @example 0
             */
            clientMarkup?: number;
        };
        ClientDto: {
            /**
             * @description ID
             * @example 69ab....
             */
            _id: string;
            /**
             * @description Название / ФИО клиента
             * @example ООО "Ромашка"
             */
            name: string;
            /**
             * @description ИНН
             * @example 2312308098
             */
            inn?: string;
            /**
             * @description КПП
             * @example 231201001
             */
            kpp?: string;
            /**
             * @description Контактное лицо
             * @example Иванов Иван Иванович
             */
            contactPerson?: string;
            /**
             * @description Телефон
             * @example +7 (918) 123-45-67
             */
            phone?: string;
            /**
             * @description E-mail
             * @example client@mail.ru
             */
            email?: string;
            /**
             * @description Реквизиты клиента
             * @example ИНН 2312..., КПП ...
             */
            requisites?: string;
            /**
             * @description Адрес
             * @example г. Краснодар, ул. Примерная, д. 1
             */
            address?: string;
            /**
             * @description Заметки
             * @example Заметки по клиенту
             */
            notes?: string;
            /**
             * @description Скидка, %
             * @example 5
             */
            discount?: number;
        };
        UpdateClientDto: {
            /**
             * @description Название / ФИО клиента
             * @example ООО "Ромашка"
             */
            name?: string;
            /**
             * @description ИНН
             * @example 2312308098
             */
            inn?: string;
            /**
             * @description КПП
             * @example 231201001
             */
            kpp?: string;
            /**
             * @description Контактное лицо
             * @example Иванов Иван Иванович
             */
            contactPerson?: string;
            /**
             * @description Телефон
             * @example +7 (918) 123-45-67
             */
            phone?: string;
            /**
             * @description E-mail
             * @example client@mail.ru
             */
            email?: string;
            /**
             * @description Реквизиты клиента
             * @example ИНН 2312..., КПП ...
             */
            requisites?: string;
            /**
             * @description Адрес
             * @example г. Краснодар, ул. Примерная, д. 1
             */
            address?: string;
            /**
             * @description Заметки
             * @example Заметки по клиенту
             */
            notes?: string;
            /**
             * @description Скидка, %
             * @example 5
             */
            discount?: number;
            /**
             * @description Наценка клиента, %
             * @example 0
             */
            clientMarkup?: number;
        };
        CategoryDto: {
            /** @example 65f8a1b2c3d4e5f6a7b8c9d0 */
            _id: string;
            /** @example Спортивное оборудование */
            name: string;
            /** @example Товары для спорта и активного отдыха */
            description?: string;
            /**
             * @description ID родительской категории или null
             * @example 65f8a1b2c3d4e5f6a7b8c9d1
             */
            parentCategoryId?: Record<string, never>;
        };
        CreateCategoryDto: {
            /**
             * @description Название категории
             * @example Спортивное оборудование
             */
            name: string;
        };
        CategoryShortDto: {
            /**
             * @description ID категории
             * @example 65f8a1b2c3d4e5f6a7b8c9d0
             */
            _id: string;
            /**
             * @description Название категории
             * @example Офисная мебель
             */
            name: string;
        };
        ProductResponseDto: {
            /**
             * @description ID продукта
             * @example 65f8a1b2c3d4e5f6a7b8c9d0
             */
            _id: string;
            /**
             * @description Артикул / внутренняя маркировка товара
             * @example P-001
             */
            sku: string;
            /**
             * @description Название продукта
             * @example Скамья парковая
             */
            name: string;
            /** @description Краткая информация о категории (после populate) */
            categoryId: components["schemas"]["CategoryShortDto"];
            /**
             * @description Бренд / торговая марка
             * @example TI-IT
             */
            brand?: string;
            /**
             * @description Описание продукта
             * @example Мебель для офиса
             */
            description?: string;
            /**
             * @description Назначение изделия
             * @example Для парков
             */
            intendedUse?: string;
            /**
             * @description Базовая продажная цена, ₽
             * @example 5000
             */
            basePrice?: number;
            /**
             * @description Текущая продажная цена, ₽
             * @example 5200
             */
            salePrice?: number;
            /**
             * @description Ссылка на изображение товара
             * @example https://example.com/table.jpg
             */
            imageUrl?: string;
            /**
             * @description Дата создания записи о товаре
             * @example 2025-02-28T12:34:56.789Z
             */
            createdAt: string;
            /**
             * @description Дата последнего обновления товара
             * @example 2025-02-28T12:34:56.789Z
             */
            updatedAt: string;
        };
        CreateProductDto: {
            /**
             * @description Артикул
             * @example P-001
             */
            sku: string;
            /**
             * @description Название товара
             * @example Скамья парковая
             */
            name: string;
            /**
             * @description Категория
             * @example 65f8a1b2c3d4e5f6a7b8c9d0
             */
            categoryId: string;
            /**
             * @description Длина, мм
             * @example 1200
             */
            lengthMm?: number;
            /**
             * @description Ширина, мм
             * @example 500
             */
            widthMm?: number;
            /**
             * @description Высота, мм
             * @example 450
             */
            heightMm?: number;
            /**
             * @description Вес, кг
             * @example 25.5
             */
            weightKg?: number;
            /**
             * @description Себестоимость, ₽
             * @example 3500
             */
            costPrice?: number;
            /**
             * @description Базовая цена, ₽
             * @example 5000
             */
            basePrice?: number;
            /**
             * @description Цена продажи, ₽
             * @example 5200
             */
            salePrice?: number;
            /**
             * @description Описание
             * @example Мебель для офиса
             */
            description?: string;
            /**
             * @description Назначение
             * @example Для парков
             */
            intendedUse?: string;
            /**
             * @description Бренд
             * @example TI-IT
             */
            brand?: string;
            /**
             * @description Ссылка на изображение
             * @example https://example.com/table.jpg
             */
            imageUrl?: string;
            /**
             * @description Цвет
             * @example white
             */
            color?: string;
        };
        ProposalItemDto: {
            /** @description Наименование позиции */
            name: string;
            /** @description Цена, ₽ */
            price: number;
            /** @description Количество */
            quantity: number;
            /** @description Ед. изм. */
            unit?: string;
            /** @description Скидка, % */
            discount?: number;
            /** @description Своя позиция */
            isCustom?: boolean;
            /** @description Картинка позиции */
            imageUrl?: string;
            /** @description Цвет позиции */
            color?: string;
        };
        CreateProposalDto: {
            /**
             * @description Организация
             * @example 69aaf2f62959200b2e9d80cb
             */
            organizationId: string;
            /**
             * @description Клиент
             * @example 69abclientid...
             */
            clientId?: string;
            /**
             * @description Доп. наценка, %
             * @example 0
             */
            extraMarkupPercent?: number;
            /**
             * @description Номер КП
             * @example 2411_32
             */
            number?: string;
            /** @description Позиции */
            items: components["schemas"]["ProposalItemDto"][];
            /**
             * @description Общая скидка, %
             * @default 0
             */
            totalDiscount: number;
            /**
             * @description Статус КП
             * @default draft
             * @enum {string}
             */
            status: "draft" | "sent" | "accepted" | "rejected";
            /**
             * @description Стиль шаблона
             * @default classic
             * @enum {string}
             */
            templateStyle: "classic" | "modern" | "minimalist";
            /** @description Надписи внизу КП */
            footerNotes?: string;
            /**
             * @description Доставка (с/без)
             * @enum {string}
             */
            deliveryOption?: "with" | "without";
        };
        UpdateProposalDto: {
            /**
             * @description Организация
             * @example 69aaf2f62959200b2e9d80cb
             */
            organizationId?: string;
            /**
             * @description Клиент
             * @example 69abclientid...
             */
            clientId?: string;
            /**
             * @description Доп. наценка, %
             * @example 0
             */
            extraMarkupPercent?: number;
            /**
             * @description Номер КП
             * @example 2411_32
             */
            number?: string;
            /** @description Позиции */
            items?: components["schemas"]["ProposalItemDto"][];
            /**
             * @description Общая скидка, %
             * @default 0
             */
            totalDiscount: number;
            /**
             * @description Статус КП
             * @default draft
             * @enum {string}
             */
            status: "draft" | "sent" | "accepted" | "rejected";
            /**
             * @description Стиль шаблона
             * @default classic
             * @enum {string}
             */
            templateStyle: "classic" | "modern" | "minimalist";
            /** @description Надписи внизу КП */
            footerNotes?: string;
            /**
             * @description Доставка (с/без)
             * @enum {string}
             */
            deliveryOption?: "with" | "without";
        };
        GoogleLoginDto: Record<string, never>;
        LocalRegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example StrongPassword123 */
            password: string;
            /** @example Иван Петров */
            name?: string;
            /**
             * @description Код приглашения
             * @example ABC123
             */
            inviteCode: string;
        };
        LocalLoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example StrongPassword123 */
            password: string;
        };
        CreateInviteDto: {
            /**
             * @description Email приглашаемого пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Имя пользователя для удобства
             * @example Иван Петров
             */
            name?: string;
            /**
             * @description Код приглашения. Если не указан, будет сгенерирован автоматически.
             * @example ABC12345
             */
            code?: string;
        };
        CurrencySettingsDto: {
            rate?: number;
            baseRateForProducts?: number;
            currencyCode?: string;
            updatedAt?: string;
        };
        KpFooterSettingsDto: {
            withDelivery?: string;
            withoutDelivery?: string;
            footerPresets?: Record<string, never>;
        };
        FontSettingsDto: {
            fontFamily?: string;
            fontSize?: number;
        };
        CreateSettingsDto: {
            /** @default global */
            key: string;
            currency?: components["schemas"]["CurrencySettingsDto"];
            kpFooter?: components["schemas"]["KpFooterSettingsDto"];
            font?: components["schemas"]["FontSettingsDto"];
        };
        UpdateSettingsDto: {
            /** @default global */
            key: string;
            currency?: components["schemas"]["CurrencySettingsDto"];
            kpFooter?: components["schemas"]["KpFooterSettingsDto"];
            font?: components["schemas"]["FontSettingsDto"];
        };
        CreatePartTypeDto: Record<string, never>;
        UpdatePartTypeDto: Record<string, never>;
        CreateMaterialDto: Record<string, never>;
        UpdateMaterialDto: Record<string, never>;
        ProductSpecificationDto: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrencyController_getRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список всех организаций */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDto"][];
                };
            };
        };
    };
    OrganizationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            /** @description Организация успешно создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDto"];
                };
            };
        };
    };
    OrganizationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Данные организации */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDto"];
                };
            };
            /** @description Организация не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Организация удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            /** @description Организация успешно обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDto"];
                };
            };
        };
    };
    OrganizationsController_importExcel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_uploadLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_uploadSignature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_uploadStamp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"][];
                };
            };
        };
    };
    ClientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
        };
    };
    ClientsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
        };
    };
    ClientsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
        };
    };
    ClientsController_importExcel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAllCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
        };
    };
    ProductsController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    ProductsController_search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseDto"][];
                };
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_exportToExcel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_importXlsx: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_importExcel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProposalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_previewPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProposalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProposalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_sendToYougile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_removeFromYougile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProposalsController_generatePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PdfTemplatesController_getBaseTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PdfTemplatesController_getByOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PdfTemplatesController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PdfTemplatesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalRegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_importExcel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_getPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_updatePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExcelController_exportAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выгрузка всех данных в Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    ImportController_importAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RealtimeController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список всех настроек */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_getGlobal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройки (создаются по умолчанию, если нет) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSettingsDto"];
            };
        };
        responses: {
            /** @description Настройки созданы */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_updateGlobal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsDto"];
            };
        };
        responses: {
            /** @description Настройки обновлены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Настройки удалены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsDto"];
            };
        };
        responses: {
            /** @description Настройки обновлены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartTypesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartTypesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartTypesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PartTypesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePartTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMaterialDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMaterialDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSpecificationController_getForProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductSpecificationController_replaceForProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductSpecificationDto"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}

/** Shortcut Aliases **/
export type Schemas = components["schemas"];
export type OrganizationDto = Schemas["OrganizationDto"];
export type CreateOrganizationDto = Schemas["CreateOrganizationDto"];

export type ProductDto = Schemas["ProductResponseDto"];
export type CreateProductDto = Schemas["CreateProductDto"];

export type CategoryDto = Schemas["CategoryDto"];
export type CreateCategoryDto = Schemas["CreateCategoryDto"];

export type ProposalItemDto = Schemas["ProposalItemDto"];
export type CreateProposalDto = Schemas["CreateProposalDto"];
export interface ProposalDto {
  _id: string;
  number: string;
  organizationId: unknown;
  items: ProposalItemDto[];
  totalDiscount: number;
  status: 'draft' | 'sent' | 'accepted' | 'rejected';
  templateStyle: string;
  createdAt: string;
  updatedAt: string;
}

export type ClientDto = Schemas["ClientDto"];
export type CreateClientDto = Schemas["CreateClientDto"];
